# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: restful_api_books_db_user
#       POSTGRES_PASSWORD: Auu2mdPwd3gay8pa3ja7jDkeWQKthFtk
#       POSTGRES_DB: restful_api_books_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - db-data:/var/lib/postgresql/data

#   backend:
#     build:
#       context: ./backend
#     environment:
#       DATABASE_URL: postgresql://restful_api_books_db_user:Auu2mdPwd3gay8pa3ja7jDkeWQKthFtk@db:5432/restful_api_books_db
#     ports:
#       - "4000:4000"
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: postgresql://restful_api_books_db_user:Auu2mdPwd3gay8pa3ja7jDkeWQKthFtk@db:5432/restful_api_books_db
#     depends_on:
#       - backend

# volumes:
#   db-data:
